datasource.properties.yaml.path: ./config/datasource.yml
liquibase.properties.yaml.path: ./config/liquibase.yml
server:
  port: 8443
  keyPassword: changeit
  keyStore: keyStore/ssl-server.jks
  keyStoreProvider: SUN
  keyStoreType: JKS
security:
  jwt:
    token:
      secretKey: secret-key
      expireLength: 300000

spring:
  datasource:
    url: jdbc:h2:mem:TestDB
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.HSQLDialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  liquibase:
    change-log: classpath:/liquibase/changelog/changelog-master.xml

logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE