datasource.properties.yaml.path: ./config/datasource.yml
liquibase.properties.yaml.path: ./config/liquibase.yml
server:
  port: 8443
  keyPassword: changeit
  keyStore: keyStore/ssl-server.jks
  keyStoreProvider: SUN
  keyStoreType: JKS
security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 3000000 # 5 minutes duration by default: 50 minutes * 60 seconds * 1000 miliseconds