datasource.properties.yaml.path: ./server/hton/config/datasource.yml
liquibase.properties.yaml.path: ./server/hton/config/liquibase.yml
server:
  port: 8443
  keyPassword: changeit
  keyStore: keyStore/ssl-server.jks
  keyStoreProvider: SUN
  keyStoreType: JKS
