#spring:
#  server:
#    port: 8443
#    ssl:
#      key-alias: selfsigned_localhost_sslserver
#      key-password: changeit
#      key-store: classpath:/keyStore/ssl-server.jks
#      key-store-provider: SUN
#      key-store-type: JKS
